version: "3.3"

services:
  icecast:
    image: moul/icecast
    ports:
      - "8020:8020"
    networks:
      - nginx_network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./icecast/icecast.xml:/etc/icecast2/icecast.xml
    restart: always

  raddb:
    image: postgres
    environment:
      - POSTGRES_DB=radman
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - db_network

  radweb:
    image: docker.pkg.github.com/dbtek/radman/radman:2.1.2
    environment:
      - PORT=8000
      - ALLOWED_HOSTS=example.com,127.0.0.1,172.19.0.3
      - DATABASE_HOST=raddb
      - DATABASE_PORT=5432
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=radman
      - DJANGO_SETTINGS_MODULE=radman.settings.prod
    depends_on:
      - raddb
    networks:
      - nginx_network
      - db_network

  nginx:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    volumes:
      - ./nginx/conf.d:/etc/nginx/user.conf.d:ro
      - ./nginx/logs:/etc/nginx/logs
      - letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTBOT_EMAIL=me@email
    networks:
      - nginx_network


networks:
  nginx_network:
    external: true
  db_network:

volumes:
    letsencrypt: