version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=radman
      - POSTGRES_USER=r4dman
      - POSTGRES_PASSWORD=secr3t
  web:
    image: docker.pkg.github.com/dbtek/radman/radman
    environment:
      - PORT=8000
      - ALLOWED_HOSTS=localhost
      - DATABASE_HOST=db
      - DATABASE_USER=r4dman
      - DATABASE_PASSWORD=secr3t
      - DATABASE_NAME=radman
      - DJANGO_SETTINGS_MODULE=radman.settings.prod
    expose:
      - 8000
    depends_on:
      - db
  proxy:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/etc/nginx/logs
    ports:
      - "80:80"