# Generated by Django 3.0.5 on 2020-06-05 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0012_auto_20200605_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='ip')),
                ('browser', models.TextField(blank=True, null=True, verbose_name='Web Browser')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name - Surname')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('mount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stations.Mount', verbose_name='Mount')),
            ],
            options={
                'verbose_name': 'Listener log',
                'verbose_name_plural': 'Listener logs',
            },
        ),
    ]
