# Generated by Django 3.0.5 on 2020-06-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplayer', '0002_auto_20200605_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenerlog',
            name='organization',
            field=models.TextField(blank=True, null=True, verbose_name='Organization'),
        ),
    ]
