# Generated by Django 3.0.5 on 2020-06-10 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0014_auto_20200610_1814'),
        ('webplayer', '0004_auto_20200606_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listenerlog',
            name='mount',
        ),
        migrations.AddField(
            model_name='listenerlog',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stations.Player', verbose_name='Player'),
        ),
    ]
