# Generated by Django 3.0.5 on 2020-12-29 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0020_auto_20201229_1557'),
        ('webplayer', '0005_auto_20200610_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenerlog',
            name='video_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stations.VideoPlayer', verbose_name='Player'),
        ),
    ]
