# Generated by Django 3.0.5 on 2020-04-25 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('station_id', models.IntegerField()),
                ('base_url', models.CharField(max_length=500)),
                ('api_key', models.CharField(max_length=500)),
            ],
        ),
    ]
