# Generated by Django 3.0.5 on 2020-04-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='port',
            field=models.CharField(default=8020, max_length=10),
            preserve_default=False,
        ),
    ]
