# Generated by Django 3.0.5 on 2020-04-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_mount_mount_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='admin_password',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='source_password',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
