# Generated by Django 3.0.5 on 2020-04-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_auto_20200426_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mount',
            name='mount_path',
        ),
    ]
