# Generated by Django 3.0.5 on 2020-04-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_mount_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mount',
            name='password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
