# Generated by Django 3.0.5 on 2020-05-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_auto_20200430_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='mount',
            name='mount_point',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
