# Generated by Django 3.0.5 on 2020-06-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0010_mount_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mount',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
