# Generated by Django 3.0.5 on 2020-06-10 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0013_mount_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mount',
            name='active',
        ),
        migrations.RemoveField(
            model_name='mount',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mount',
            name='password',
        ),
        migrations.RemoveField(
            model_name='mount',
            name='slug',
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('mount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.Mount', verbose_name='Dinleme Noktası')),
            ],
        ),
    ]
