# Generated by Django 3.0.5 on 2020-11-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0017_auto_20201105_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='station',
            name='station_id',
        ),
    ]
