# Generated by Django 3.0.5 on 2020-11-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0018_auto_20201116_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='admin_password',
        ),
    ]
